
#Districts Recors
distritos:
 - Kamavota:
    xpath: '//*[@id="orgUnitiOs7EQeuLLG"]/a'

 - Kamaxakeni:
    xpath: '//*[@id="orgUnitAVjKUWRgKBG"]/a'

 - Kampfumu:
     xpath: '//*[@id="orgUnitPtWKKinaEXb"]/a'

 - Kamubukwana:
    xpath: '//*[@id="orgUnitat6Mv4Zw321"]/a'

 - Kanyaka:
    xpath: '//*[@id="orgUnitBFNOLjUjAoG"]/a'

 - Katembe:
    xpath: '//*[@id="orgUnitCVwHv6utuLy"]/a'

 - Nlhamankulu:
    xpath: '//*[@id="orgUnitc1N79yeN7S2"]/a'



