#Districts Records
distritos:
 - Kamaxakeni:
     xpath: '//*[@id="orgUnitAVjKUWRgKBG"]/a'

 - Kampfumu:
     xpath: '//*[@id="orgUnitPtWKKinaEXb"]/a'

 - Kamubukwana:
     xpath: '//*[@id="orgUnitat6Mv4Zw321"]/a'

 - Kanyaka:
    xpath: '//*[@id="orgUnitBFNOLjUjAoG"]/a'

 - Katembe:
    xpath: '//*[@id="orgUnitCVwHv6utuLy"]/a'

 - Nlhamankulu:
    xpath: '//*[@id="orgUnitc1N79yeN7S2"]/a'


#US Records: Kamavota
unidades_sanitarias:
-  1_de_junho_cs:
    name: 1 de junho
    district: Kamavota
    province: Maputo
    xpath: '//*[@id="orgUnitFTLV9nOnAFC"]/a'

-  albasine_cs:
    name: Albasine CS
    district: Kamavota
    province: Maputo
    xpath: '//*[@id="orgUnitz8g2CUKUMCF"]/a'

-  hulene_psa:
    name: Huelene PSA
    district: Kamavota
    province: Maputo
    xpath: '//*[@id="orgUnitMa6u8rJ3faa"]/a'

-  mavalane_cs:
    name: Mavalane CS
    district: Kamavota
    province: Maputo
    xpath: '//*[@id="orgUnitwafWzemVbX4"]/a'

-  mavalane_hg:
    name: Mavalane HG
    district: Kamavota
    province: Maputo
    xpath: '//*[@id="orgUnitwafWzemVbX4"]/a'

-  pescadores_ps:
    name: Pescadores PS
    district: Kamavota
    province: Maputo
    xpath: '//*[@id="orgUnitXNYN71gD1ps"]/a'

-  romao_psa:
    name: Romao PSA
    district: Kamavota
    province: Maputo
    xpath: '//*[@id="orgUnitcEqnyE9ahXG"]/a'


 #US Records: Kamaxakeni
-  1_de_maio_cs:
    name: 1 de maio
    district: Kamaxakeni
    province: Maputo
    xpath: '//*[@id="orgUnitiv9D81uQSZc"]/a'

-  polana_canico_cs:
    name: Polana Canico CS
    district: Kamaxakeni
    province: Maputo
    xpath: '//*[@id="orgUnitehepVdZYP6u"]/a'


#US Records: Kampfumu
-  1_alto_mae_csurb:
    name: 1 de maio
    district: Kampfumu
    province: Maputo
    xpath: '//*[@id="orgUnitkt468XD802Y"]/a'

-  hospital_central_de_mapito_hc:
    name: Hopsital Central de Maputo HC
    district: Kampfumu
    province: Maputo
    xpath: '//*[@id="orgUnitvLT0ry3CDSL"]/a'

-  hospital_central_pediatrico_de_mapito_hc:
    name: Hopsital Central Pediatrico de Maputo HC
    district: Kampfumu
    province: Maputo
    xpath: '//*[@id="orgUnitaMaDE2B3W0b"]/a'

-  malhangalene_cs:
    name: Malhangalene CS
    district: Kampfumu
    province: Maputo
    xpath: '//*[@id="orgUnitDFudgV3AdHI"]/a'

-  maxaquene_csurb:
    name: Maxaquene CSURB
    district: Kampfumu
    province: Maputo
    xpath: '//*[@id="orgUnitDz4coB1P1l5"]/a'

-  Hospital_militar_de_maputo:
    name: Hospital Militar de Maputo
    district: Kampfumu
    province: Maputo
    xpath: '//*[@id="orgUnitLU2ynwYvl51"]/a'

-  polana_cimento_csurb:
    name: Polana Cimento CSURB
    district: Kampfumu
    province: Maputo
    xpath: '//*[@id="orgUnityGhwOKR4gBj"]/a'

-  porto_csurb:
    name: Porto CSURB
    district: Kampfumu
    province: Maputo
    xpath: '//*[@id="orgUnitDoyPc35A7zI"]/a'


#US Records: Kamubukwana

-  bagamoio_cs:
    name: Bagamoio CS
    district: Kamubukwana
    province: Maputo
    xpath: '//*[@id="orgUnitaywqWn0Qkf8"]/a'

-  hospital_psiquiatrico_do_infulene_cs:
    name: Hospital Psiquiatrico do Infulene HP
    district: Kamubukwana
    province: Maputo
    xpath: '//*[@id="orgUnitQzORjiSM4Yz"]/a'

-  inhagoia_ps:
    name: Inhagoia PS
    district: Kamubukwana
    province: Maputo
    xpath: '//*[@id="orgUnitEysXJHRv7xJ"]/a'

-  magoanine_tenda_psa:
    name: Magoanine Tenda PSA
    district: Kamubukwana
    province: Maputo
    xpath: '//*[@id="orgUnito4HThkC2OEY"]/a'

-  zimpeto_ps:
    name: Zimpeto PS
    district: Kamubukwana
    province: Maputo
    xpath: '//*[@id="orgUnitKxezVOQ2TVR"]/a'


#US Records: Kanyaka
-  inhaca_ps:
    name: Inhaca PS
    district: Kanyaka
    province: Maputo
    xpath: '//*[@id="orgUnitGJaIp0bKoXH"]/a'


#US Records: Katembe
-  catembe_cs:
    name: Catembe CS
    district: Katembe
    province: Maputo
    xpath: '//*[@id="orgUnitRYReGTxpYTF"]/a'

-  chamissava_cs:
    name: Chamissava CS
    district: Katembe
    province: Maputo
    xpath: '//*[@id="orgUnitNeiXUPnpjto"]/a'

-  incassane_cs:
    name: Incassane PSA
    district: Katembe
    province: Maputo
    xpath: '//*[@id="orgUnitMaU3nWtTalb"]/a'

-  mutsekwa_ps:
    name: Mutsekwa PS
    district: Katembe
    province: Maputo
    xpath: '//*[@id="orgUnitqWYxCOCbEx4"]/a'


#US Records: Nlhamankulu

-  centro_de_saude_do_chamanculo_cs:
    name: Centro de Saude do Chamanculo CS
    district: Nlhamankulu
    province: Maputo
    xpath: '//*[@id="orgUnitCtlQF8Vac9k"]/a'

-  chamanculo_hg:
    name: Chamanculo HG
    district: Nlhamankulu
    province: Maputo
    xpath: '//*[@id="orgUnitg0bRtxKVUVQ"]/a'

-  jose_macamo_cs:
    name: Jose Macamo CS
    district: Nlhamankulu
    province: Maputo
    xpath: '//*[@id="orgUnitpB4dqFQTJix"]/a'

-  jose_macamo_HG:
    name: Jose Macamo HG
    district: Nlhamankulu
    province: Maputo
    xpath: '//*[@id="orgUnityrfeiAhBKeO"]/a'

-  xipamanine_csurb:
    name: Xipamanine CSURB
    district: Nlhamankulu
    province: Maputo
    xpath: '//*[@id="orgUnitsWChmRhN9eS"]/a'